# CI testing values for appmesh-controller

# This is a dummy account for CI test. Not a valid account ID
accountId: 123456789
region: us-west-2
image:
  repository: public.ecr.aws/appmesh/appmesh-controller
  tag: v1.9.0
  pullPolicy: IfNotPresent
