fullnameOverride: calico

serviceAccount:
  create: true

calico:
  tag: v3.8.1
  typha:
    image: quay.io/calico/typha
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "96Mi"
        cpu: "100m"
  node:
    image: quay.io/calico/node
    resources:
      requests:
        memory: "32Mi"
        cpu: "20m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  typha_autoscaler:
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "10m"

autoscaler:
  tag: "1.1.2"
  image: k8s.gcr.io/cluster-proportional-autoscaler-amd64