apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-cloudwatch-metrics.fullname" . }}
  labels:
    {{- include "aws-cloudwatch-metrics.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{$key }}: |
    {{- $value | nindent 4 }}
{{- end }}