# Default values for aws-vpc-cni.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This default name override is to maintain backwards compatability with
# existing naming
nameOverride: aws-node

image:
  region: us-west-2
  tag: v1.6.2
  pullPolicy: Always
  # Set to use custom image
  # override: "repo/org/image:tag"

# The CNI supports a number of environment variable settings
# See https://github.com/aws/amazon-vpc-cni-k8s#cni-configuration-variables
env:
  AWS_VPC_K8S_CNI_LOGLEVEL: DEBUG
  AWS_VPC_K8S_CNI_VETHPREFIX: eni
  AWS_VPC_ENI_MTU: "9001"

# this flag enables you to use the match label that was present in the original daemonset deployed by EKS
# You can then annotate and label the original aws-node resources and 'adopt' them into a helm release
originalMatchLabels: false

cniConfig: 
  enabled: false
  fileContents: ""

imagePullSecrets: []

fullnameOverride: "aws-node"

priorityClassName: system-node-critical

podSecurityContext: {}

podAnnotations: {}

securityContext:
  privileged: true

crd:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME

resources:
  requests:
    cpu: 10m

updateStrategy:
  type: RollingUpdate

nodeSelector: {}

tolerations: []

affinity: {}
