{{- if .Values.cniConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-vpc-cni.fullname" . }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
binaryData:
  10-aws.conflist: {{ .Values.cniConfig.fileContents | b64enc }}
{{- end }}
---
{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nameOverride | default "amazon-vpc-cni-settings" }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
data:
  enable-windows-ipam: {{ .Values.enableWindowsIpam | quote }}
  enable-network-policy-controller: {{ .Values.enableNetworkPolicy | quote }}
  enable-windows-prefix-delegation: {{ .Values.enableWindowsPrefixDelegation | quote }}
  warm-prefix-target: {{ .Values.warmWindowsPrefixTarget | quote }}
  warm-ip-target: {{ .Values.warmWindowsIPTarget | quote }}
  minimum-ip-target: {{ .Values.minimumWindowsIPTarget | quote }}
  branch-eni-cooldown: {{ .Values.branchENICooldown | quote }}
{{- end }}