# This file contains configuration for the webhooks defined
# in the appmesh-controller. The contents should not be changed
# unless there are corresponding changes in the appmesh-controller
# controller. This file is referenced in the templates for
# generating the admission webhooks for the resources
customResources:
  - name: gatewayroute
    resource: gatewayroutes
  - name: mesh
    resource: meshes
  - name: virtualnode
    resource: virtualnodes
  - name: virtualrouter
    resource: virtualrouters
  - name: virtualservice
    resource: virtualservices
  - name: virtualgateway
    resource: virtualgateways
  - name: backendgroup
    resource: backendgroups
