name: Update EFA Device Plugin Instance Types

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 18 * * 1-5" # Every Monday at 10:00 PT

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  generate-limits:
    if: github.repository == 'aws/eks-charts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # refs/tags/v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # refs/tags/v4.0.2
        with:
          role-to-assume: ${{ secrets.UPDATE_CHARTS_AWS_ROLE_ARN }}
          role-duration-seconds: 900 #
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run ./hack/update-efa-instance-types.sh
        run: |
              YQ_VERSION=v4.2.0
              YQ_PLATFORM=linux_amd64
              wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_${YQ_PLATFORM} -O /usr/local/bin/yq &&\
                chmod +x /usr/local/bin/yq

              ./hack/update-efa-instance-types.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # refs/tags/v7.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(efa-device-plugin): add latest EFA instance types
          title: "chore(efa-device-plugin): add latest EFA instance types"
          body: |
            This PR updates adds the latest EFA supported instance types to the EFA device plugin chart by running `./hack/update-efa-instance-types.sh`.
            
            ## Testing
            Please verify that the generated limits are correct.
          branch: automated/update-efa-instance-types
          base: master
          delete-branch: true